backend:
  name: github
  repo: tranthaison1231/STATER_GATSBY
  branch: master # Branch to update (optional; defaults to master)
publish_mode: editorial_workflow
media_library:
  name: cloudinary
  config:
    cloud_name: coders-tokyo-shyn
    api_key: 914168869417659
collections:
  - name: blog
    label: Blog
    folder: 'content/blog'
    create: true
    fields:
      - { name: date, label: Date, widget: 'date' }
      - { name: title, label: Title, widget: 'string' }
      - { name: image, label: Image, widget: 'image' }
      - { name: body, label: Body, widget: 'markdown' }
