backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_library:
  name: cloudinary
  config:
    cloud_name: coders-tokyo-shyn
    api_key: 914168869417659
collections:
  - name: blog
    label: Blog
    folder: 'content/posts'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - {
          name: 'template',
          label: 'Template',
          widget: 'hidden',
          default: 'post',
        }
      - {
          label: 'Highlight Posts',
          name: 'isHighlight',
          widget: 'boolean',
          default: false,
        }
      - { name: 'name', label: 'Name', widget: 'string' }
      - { name: date, label: Date, widget: 'date' }
      - { name: title, label: Title, widget: 'markdown' }
      - { name: image, label: Image, widget: 'image' }
      - { name: body, label: Body, widget: 'markdown' }
  - name: project
    label: Project
    folder: 'content/projects'
    create: true
    fields:
      - {
          name: 'template',
          label: 'Template',
          widget: 'hidden',
          default: 'project',
        }
      - { name: date, label: Date, widget: 'date' }
      - { name: title, label: Title, widget: 'string' }
      - { name: image, label: Image, widget: 'image' }
      - { name: body, label: Body, widget: 'markdown' }
  - name: page
    label: Page
    folder: 'content/pages'
    create: true
    fields:
      - {
          name: 'template',
          label: 'Template',
          widget: 'hidden',
          default: 'page',
        }
      - { name: date, label: Date, widget: 'date' }
      - { name: title, label: Title, widget: 'string' }
      - { name: image, label: Image, widget: 'image' }
      - { name: body, label: Body, widget: 'markdown' }
